### ISSUE TITLE
通过ytrace_enable开启会报错

### ISSUE THREAD

**Issue by yaowenqiang** [yangxikun/ytrace#2]
[33317.532893] php-fpm7.1[29624]: segfault at 18 ip 00007f20a2aaea19 sp 00007ffd63b6dd60 error 4 in ytrace.so[7f20a2aab000+8000]

**Comment by yangxikun** [comment]
1、麻烦贴下php版本：`php -v`。
2、`make test`的时候是否有失败的测试用例。
3、是否有开启xdebug、zend OPcache、xhprof等其他zend扩展。

**Comment by yangxikun** [comment]
php 7下确实存在coredump的情况，预计在这周fix

**Comment by yangxikun** [comment]
解决了一处php 7 coredump问题，麻烦验证下

**Comment by long904** [comment]
请问是需要在 PHP 代码里加入 php function 吗？编译了so 了，但/tmp/ytrace目录下没有产生任何文件。

**Comment by yangxikun** [comment]
可以看下这篇文章，简单介绍了如何使用：https://juejin.im/post/5a1c260a6fb9a0450002c797?utm_source=wechat

你的ini怎么配置的

**Comment by long904** [comment]
ini 在原有基础上加入以下：
extension=ytrace.so
ytrace.output_dir=/tmp/ytrace
ytrace.output_format=%R_%t
ytrace.enable_trigger=1
ytrace.enable_trigger_value=ytrace

PHP 版本为5.6，已成功价值 ytrace.so 扩展，完成后重启 fpm ，在/tmp 目录下没有产生任何文件。手动建立/tmp/ytrace 也没有。

**Comment by long904** [comment]
补充，我并没有安装 webui 和 chrome扩展，是否跟这些有关系呢。

**Comment by yangxikun** [comment]
chrome扩展是用来往请求里插入cookie的，ytrace会从cookie检测是否启用跟踪（当ytrace.enable_trigger=1，且ytrace.auto_enable=0）。
如果设置ytrace.auto_enable=1，则会始终进行跟踪。
建议按照我的文章来操作，同时看下对应的文档。
