### ISSUE TITLE
扩展安装完之后看不到效果

### ISSUE THREAD

**Issue by chenishr** [yangxikun/ytrace#3]
您好，我是根据 [这篇文章][1] 来进行安装配置的，但是整个流程都完成之后，没有看到相应的效果，实在不知道是怎么回事了。

* 扩展安装成功：  
<img width="539" alt="screen shot 2017-12-03 at 10 31 44 am" src="https://user-images.githubusercontent.com/5761817/33521730-3da2402c-d815-11e7-8326-afe8928e4e8d.png">

* 扩展的配置：
<img width="502" alt="screen shot 2017-12-03 at 10 33 29 am" src="https://user-images.githubusercontent.com/5761817/33521736-761dfdb0-d815-11e7-8194-5e94ea19dca3.png">

* chrome 扩展使用的是默认值
<img width="765" alt="screen shot 2017-12-03 at 10 37 46 am" src="https://user-images.githubusercontent.com/5761817/33521833-2ff66d24-d818-11e7-8cda-993da85338c4.png">

* 看不到效果：
<img width="753" alt="screen shot 2017-12-03 at 10 34 46 am" src="https://user-images.githubusercontent.com/5761817/33521745-b2b33894-d815-11e7-8201-55ad9dbf1a27.png">

请问这会是什么问题，我应该怎么解决呢？

谢谢！

[1]: https://juejin.im/post/5a1c260a6fb9a0450002c797?utm_source=wechat

**Comment by yangxikun** [comment]
在需要调试的网页下，点击chrome扩展，会弹出如下截图：
![](https://github.com/yangxikun/ytrace_chrome_extension/raw/master/img/popup.png)

勾选YTRACE_TRIGGER，填上ini配置中的`ytrace.enable_trigger_value`配置的值，即`ytrace`，保存。
再刷新下调试网页就可以了。

chrome扩展是用来往cookie里设置Ytrace相关配置的。

**Comment by chenishr** [comment]
可以了，之前没有留意到右上角的 chrome 扩展图标。
