### ISSUE TITLE
make test失败

### ISSUE THREAD

**Issue by ForestFDemo** [yangxikun/ytrace#4]
错误信息：
`ace_file.lo ytrace_filter.lo
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/ytrace.so -bundle  .libs/ytrace.o .libs/ytrace_execute.o .libs/ytrace_opcode_handler_override.o .libs/ytrace_var.o .libs/ytrace_str.o .libs/ytrace_file.o .libs/ytrace_filter.o
duplicate symbol _ytrace_old_execute_ex in:
    .libs/ytrace.o
    .libs/ytrace_execute.o
duplicate symbol _ytrace_old_execute_internal in:
    .libs/ytrace.o
    .libs/ytrace_execute.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ytrace.la] Error 1`

php 版本：
`➜  ytrace git:(master) ✗ php -v
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): image not found
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies`

没有安装xdebug等相关扩展

**Comment by yangxikun** [comment]
解决了下clang编译的问题，麻烦再编译下看看。

**Comment by ForestFDemo** [comment]
删除文件夹后，拉去最新代码，重新编译安装后，依旧如下：
`➜  ytrace git:(master) ✗ git pull
Already up-to-date.
➜  ytrace git:(master) ✗ make test
/bin/sh /Users/demo/DevTool/ytrace/libtool --mode=link cc -DPHP_ATOM_INC -I/Users/demo/DevTool/ytrace/include -I/Users/demo/DevTool/ytrace/main -I/Users/demo/DevTool/ytrace -I/usr/local/Cellar/php71/7.1.8_20/include/php -I/usr/local/Cellar/php71/7.1.8_20/include/php/main -I/usr/local/Cellar/php71/7.1.8_20/include/php/TSRM -I/usr/local/Cellar/php71/7.1.8_20/include/php/Zend -I/usr/local/Cellar/php71/7.1.8_20/include/php/ext -I/usr/local/Cellar/php71/7.1.8_20/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -o ytrace.la -export-dynamic -avoid-version -prefer-pic -module -rpath /Users/demo/DevTool/ytrace/modules  ytrace.lo ytrace_execute.lo ytrace_opcode_handler_override.lo ytrace_var.lo ytrace_str.lo ytrace_file.lo ytrace_filter.lo
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/ytrace.so -bundle  .libs/ytrace.o .libs/ytrace_execute.o .libs/ytrace_opcode_handler_override.o .libs/ytrace_var.o .libs/ytrace_str.o .libs/ytrace_file.o .libs/ytrace_filter.o
duplicate symbol _ytrace_old_execute_ex in:
    .libs/ytrace.o
    .libs/ytrace_execute.o
duplicate symbol _ytrace_old_execute_internal in:
    .libs/ytrace.o
    .libs/ytrace_execute.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ytrace.la] Error 1`

**Comment by yangxikun** [comment]
大概知道是那里有问题了，头文件中不应该直接定义全局变量。
已fix，麻烦再编译下看看。

**Comment by ghost** [comment]
已经可以了，非常感谢🙏

**Comment by ghost** [comment]
好像会影响我的数据库链接，一旦我在php.ini 写了配置文件后数据库没办法链接，配置文件参考的链接为：[参考链接](https://juejin.im/post/5a1c260a6fb9a0450002c797?utm_source=wechat)

**Comment by yangxikun** [comment]
你把`extension=ytrace.so`注释掉，数据库就可以连接上了？
报了什么错误？

**Comment by ghost** [comment]
我解决了，重启服务就好了，为什么我执行命令`PHP - S `出现以下提示`➜  ytrace git:(master) ✗ php -S localhost:8088
PHP 7.1.8 Development Server started at Sun Dec  3 17:04:06 2017
Listening on http://localhost:8088
Document root is /Users/demo/DevTool/ytrace
Press Ctrl-C to quit.
`

**Comment by yangxikun** [comment]
这提示没有错误吧？
不过你应该在[ytrace_gui](https://github.com/yangxikun/ytrace_gui)项目根目录执行`php -S localhost:8088`来启动webui

**Comment by ghost** [comment]
成功了 非常感谢
