### ISSUE TITLE
YII 框架里，开启ytrace 访问页面报错

### ISSUE THREAD

**Issue by long904** [yangxikun/ytrace#5]
有个业务应用在 YII 框架里，编译了 ytrace还有 web_gui 和 chrome 扩展。但开启chrome 插入 cookie 后，页面500错误。但8088能显示并抓取到相关信息，请问这个是什么问题呢？PHP 日志里没有报错，nginx 日志500状态。

**Comment by yangxikun** [comment]
1、ytrace使用了最新代码了吗？
2、执行如下命令输出我看下：
`php --version`和`php -m`
3、把fpm worker进程设置为1，然后再启用ytrace，出现500，看下worker进程是不是挂了
4、如果fpm挂了，能否抓下coredump信息（需要php编译开启debug模式）：https://ma.ttias.be/generate-php-core-dumps-segfaults-php-fpm/
5、最好能直接给我一段导致500的测试代码

**Comment by long904** [comment]
1、代码根据这里，https://github.com/yangxikun/ytrace.git。
2、PHP 5.6.16 (cli) (built: Dec  7 2015 14:40:26) ，
      [PHP Modules]
bcmath
Core
ctype
curl
date
dom
ereg
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
memcache
memcached
mhash
molten
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
ytrace
zip
zlib

[Zend Modules]
3和4不会，而且因为我确定是采用扩展插入 cookie 进行访问，停止插件或者换其他浏览器访问是没有任何问题的。
5、这框架里涉及代码有点多，或者说我也无法给到一个具体的代码。

**Comment by long904** [comment]
补充，我把扩展的「YTRACE_TRIGGER」ytrace 这个删除就可以正常访问，或者是我改掉一个名字也行，比如 firebug 里，更改「YTRACE_TRIGGER」为「YTRACE_TRIGG」。但这样，ytrace 自然也是不能抓取相关信息了。

**Comment by yangxikun** [comment]
Ytrace是有跟踪文件产生的是吧？看下跟踪文件里显示执行到了哪里

**Comment by long904** [comment]
有的，就是页面显示500。如何看跟踪文件执行到哪里呢？怎么理解

**Comment by yangxikun** [comment]
你可以在ytrace输出目录里看到跟踪文件，打开文件，看到文件末尾，就知道跟踪到哪里了

**Comment by long904** [comment]
嗯。以某个页面为例，看到的追踪文件末尾有某个 php，那意思是把这个 php 提供给你还是？

**Comment by yangxikun** [comment]
你在出问题的那个php文件代码里，加些die，看下是在哪个位置出现了500。

**Comment by yangxikun** [comment]
no any feedback.
